
package tr.com.netas.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NetasSOAPService", targetNamespace = "http://ws.netas.com.tr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NetasSOAPService {


    /**
     * 
     * @return
     *     returns java.util.List<tr.com.netas.ws.Musteri>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "musteriler", targetNamespace = "http://ws.netas.com.tr/", className = "tr.com.netas.ws.Musteriler")
    @ResponseWrapper(localName = "musterilerResponse", targetNamespace = "http://ws.netas.com.tr/", className = "tr.com.netas.ws.MusterilerResponse")
    public List<Musteri> musteriler();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "test", targetNamespace = "http://ws.netas.com.tr/", className = "tr.com.netas.ws.Test")
    @ResponseWrapper(localName = "testResponse", targetNamespace = "http://ws.netas.com.tr/", className = "tr.com.netas.ws.TestResponse")
    public String test(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
