
package tr.com.netas.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NetasSOAPServiceService", targetNamespace = "http://ws.netas.com.tr/", wsdlLocation = "http://localhost:8080/Gun3-JAX-WS-Service/NetasSOAPService?WSDL")
public class NetasSOAPServiceService
    extends Service
{

    private final static URL NETASSOAPSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException NETASSOAPSERVICESERVICE_EXCEPTION;
    private final static QName NETASSOAPSERVICESERVICE_QNAME = new QName("http://ws.netas.com.tr/", "NetasSOAPServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Gun3-JAX-WS-Service/NetasSOAPService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NETASSOAPSERVICESERVICE_WSDL_LOCATION = url;
        NETASSOAPSERVICESERVICE_EXCEPTION = e;
    }

    public NetasSOAPServiceService() {
        super(__getWsdlLocation(), NETASSOAPSERVICESERVICE_QNAME);
    }

    public NetasSOAPServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NETASSOAPSERVICESERVICE_QNAME, features);
    }

    public NetasSOAPServiceService(URL wsdlLocation) {
        super(wsdlLocation, NETASSOAPSERVICESERVICE_QNAME);
    }

    public NetasSOAPServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NETASSOAPSERVICESERVICE_QNAME, features);
    }

    public NetasSOAPServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NetasSOAPServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NetasSOAPService
     */
    @WebEndpoint(name = "NetasSOAPServicePort")
    public NetasSOAPService getNetasSOAPServicePort() {
        return super.getPort(new QName("http://ws.netas.com.tr/", "NetasSOAPServicePort"), NetasSOAPService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NetasSOAPService
     */
    @WebEndpoint(name = "NetasSOAPServicePort")
    public NetasSOAPService getNetasSOAPServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.netas.com.tr/", "NetasSOAPServicePort"), NetasSOAPService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NETASSOAPSERVICESERVICE_EXCEPTION!= null) {
            throw NETASSOAPSERVICESERVICE_EXCEPTION;
        }
        return NETASSOAPSERVICESERVICE_WSDL_LOCATION;
    }

}
